config/routes.rb
Appv3::Application.routes.draw do
  
  scope '/backend' do
    devise_for :administrators, :registration => 'register' #, :controllers => { :sessions => "backend/sessions" }
  end
  
  get "home/index"

  match '/getStream', :to => 'streams#getStream' 
  match '/getAds', :to => 'streams#getAds'
  match '/getAds2', :to => 'streams#getAds2'
  match '/demo1' , :to => 'streams#demo1'
  match '/log_out' , :to => 'streams#log_out'
  match '/getID' , :to => 'streams#getID'
  match '/getusers', :to => 'online_users#number_users'
  match '/saveStreams', :to => 'streams#saveStreams'  
  match '/getsavedstreams', :to => 'streams#getsavedstreams'

  resources :streams

  namespace :backend do
    root to: "ads#index"
    resources :proxies
    resources :ad_slots
    resources :online_users
    resources :tags
    resources :ads
    resources :stream_slots
    resources :live_streams
    
  end

  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  

  get "sessions/new"

  get "sessions/create"

  get "sessions/destory"

  root :to => 'sessions#new'

  
  controller :sessions do
    get 'login' => :new
    get 'callback' => :callback
    get 'callback2'=> :callback2
    delete 'logout' => :destroy  #ana 3amlaha delete.. therefore in link to pass delete method.. if was get then in link_to dont pass anything like the admission application
  end
  

end

app/models/ad_slot.rb
class AdSlot < ActiveRecord::Base
  
  has_many :stream_slots, :dependent => :destroy
  has_many :live_streams, :through => :stream_slots
  
  validates :time, :presence => true
  
  def to_s
    "#{time}"
  end 
end

app/controllers/ad_slots_controller.rb
class AdSlotsController < InheritedResources::Base
end

app/helpers/ad_slots_helper.rb
module AdSlotsHelper
end

app/views/ad_slots/_form.html.erb
<%= form_for(@ad_slot) do |f| %>
  <% if @ad_slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad_slot.errors.count, "error") %> prohibited this ad_slot from being saved:</h2>

      <ul>
      <% @ad_slot.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br />
    <%= f.time_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ad_slots/edit.html.erb
<h1>Editing ad_slot</h1>

<%= render 'form' %>

<%= link_to 'Show', @ad_slot %> |
<%= link_to 'Back', ad_slots_path %>

app/views/ad_slots/index.html.erb
<h1>Listing ad_slots</h1>

<table>
  <tr>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ad_slots.each do |ad_slot| %>
  <tr>
    <td><%= ad_slot.time %></td>
    <td><%= link_to 'Show', ad_slot %></td>
    <td><%= link_to 'Edit', edit_ad_slot_path(ad_slot) %></td>
    <td><%= link_to 'Destroy', ad_slot, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ad slot', new_ad_slot_path %>

app/views/ad_slots/new.html.erb
<h1>New ad_slot</h1>

<%= render 'form' %>

<%= link_to 'Back', ad_slots_path %>

app/views/ad_slots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time:</b>
  <%= @ad_slot.time %>
</p>


<%= link_to 'Edit', edit_ad_slot_path(@ad_slot) %> |
<%= link_to 'Back', ad_slots_path %>