config/routes.rb
Appv3::Application.routes.draw do
  
  scope '/backend' do
    devise_for :administrators, :registration => 'register' #, :controllers => { :sessions => "backend/sessions" }
  end
  
  get "home/index"

  match '/getStream', :to => 'streams#getStream' 
  match '/getAds', :to => 'streams#getAds'
  match '/getAds2', :to => 'streams#getAds2'
  match '/demo1' , :to => 'streams#demo1'
  match '/log_out' , :to => 'streams#log_out'
  match '/getID' , :to => 'streams#getID'
  match '/getusers', :to => 'online_users#number_users'
  match '/saveStreams', :to => 'streams#saveStreams'  
  match '/getsavedstreams', :to => 'streams#getsavedstreams'

  resources :streams

  namespace :backend do
    root to: "ads#index"
    resources :proxies
    resources :ad_slots
    resources :online_users
    resources :tags
    resources :ads
    resources :stream_slots
    resources :live_streams
    
  end

  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  

  get "sessions/new"

  get "sessions/create"

  get "sessions/destory"

  root :to => 'sessions#new'

  
  controller :sessions do
    get 'login' => :new
    get 'callback' => :callback
    get 'callback2'=> :callback2
    delete 'logout' => :destroy  #ana 3amlaha delete.. therefore in link to pass delete method.. if was get then in link_to dont pass anything like the admission application
  end
  

end

app/models/online_user.rb
class OnlineUser < ActiveRecord::Base
  
  has_and_belongs_to_many :tags
  #has_and_belongs_to_many :ads
  
  has_many :ad_users, :dependent => :destroy
  has_many :ads, :through => :ad_users
  
  validates :name, :presence => true
  
  
  def self.number
    all.count
  end
  
end

app/controllers/online_users_controller.rb
class OnlineUsersController < InheritedResources::Base
  
  
  #respond_to :json, only: [:number_users]
  def number_users
    @data_point =  OnlineUser.number
    render :json => @data_point
  end

  
end

app/helpers/online_users_helper.rb
module OnlineUsersHelper
end

app/views/online_users/_form.html.erb
<%= form_for(@online_user) do |f| %>
  <% if @online_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@online_user.errors.count, "error") %> prohibited this online_user from being saved:</h2>

      <ul>
      <% @online_user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :plan_id %><br />
    <%= f.number_field :plan_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/online_users/edit.html.erb
<h1>Editing online_user</h1>

<%= render 'form' %>

<%= link_to 'Show', @online_user %> |
<%= link_to 'Back', online_users_path %>

app/views/online_users/index.html.erb
<h1>Listing online_users</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Plan</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @online_users.each do |online_user| %>
  <tr>
    <td><%= online_user.name %></td>
    <td><%= online_user.plan_id %></td>
    <td><%= link_to 'Show', online_user %></td>
    <td><%= link_to 'Edit', edit_online_user_path(online_user) %></td>
    <td><%= link_to 'Destroy', online_user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Online user', new_online_user_path %>

app/views/online_users/new.html.erb
<h1>New online_user</h1>

<%= render 'form' %>

<%= link_to 'Back', online_users_path %>

app/views/online_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @online_user.name %>
</p>

<p>
  <b>Plan:</b>
  <%= @online_user.plan_id %>
</p>


<%= link_to 'Edit', edit_online_user_path(@online_user) %> |
<%= link_to 'Back', online_users_path %>