config/routes.rb
Appv3::Application.routes.draw do
  
  scope '/backend' do
    devise_for :administrators, :registration => 'register' #, :controllers => { :sessions => "backend/sessions" }
  end
  
  get "home/index"

  match '/getStream', :to => 'streams#getStream' 
  match '/getAds', :to => 'streams#getAds'
  match '/getAds2', :to => 'streams#getAds2'
  match '/demo1' , :to => 'streams#demo1'
  match '/log_out' , :to => 'streams#log_out'
  match '/getID' , :to => 'streams#getID'
  match '/getusers', :to => 'online_users#number_users'
  match '/saveStreams', :to => 'streams#saveStreams'  
  match '/getsavedstreams', :to => 'streams#getsavedstreams'

  resources :streams

  namespace :backend do
    root to: "ads#index"
    resources :proxies
    resources :ad_slots
    resources :online_users
    resources :tags
    resources :ads
    resources :stream_slots
    resources :live_streams
    
  end

  

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  

  get "sessions/new"

  get "sessions/create"

  get "sessions/destory"

  root :to => 'sessions#new'

  
  controller :sessions do
    get 'login' => :new
    get 'callback' => :callback
    get 'callback2'=> :callback2
    delete 'logout' => :destroy  #ana 3amlaha delete.. therefore in link to pass delete method.. if was get then in link_to dont pass anything like the admission application
  end
  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  
  has_and_belongs_to_many :tags
  #has_and_belongs_to_many :online_users
  has_many :ad_users, :dependent => :destroy
  has_many :online_users, :through => :ad_users
  
  validates :url, :duration, :presence => true
  validates :duration , :numericality => true
  #validates :URL , :format => { :with => /(^$)|(^(http|https):\/\/[a-zA-Z0-9]+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix, :message => "Not a valid URL" }
  validates :url, :format => {:with => /(^$)|(^(http|https):\/\/[a-zA-Z0-9\/_.:]+.m3u8$)/, :message => "Invalid URL"}
  
  attr_accessor :tag_list
  accepts_nested_attributes_for :tags
  #after_save :update_tags
  
  #paginate
  #paginates_per 5

  private 

  def update_tags
    tags.delete_all
    selected_tags = tag_list.nil? ? [] : tag_list.keys.collect{|id| Tag.find_by_id(id)}
    selected_tags.each {|tag| self.tags << tag}
    #logger.debug "TAG LIST!!!!!!!!!!!!"
    #logger.debug tag_list
    
    #tag_list has values of checked checkboxes : {"23"=>"1", "24"=>"1"}
    #I can access it here.. because it is after ad -> params[ad][tag_list][22] (i think)
    # After save, will call this method.. and i can see tag_list because i made it an attr_accessor
    #as you can see the key is the tag id
    
    #The update_attributes and save methods will assign the tag_list hash from the params
    #to our accessor “tag_list” property automatically and thus provide us convenient 
    # access to the hash data in our callback handler.
    
    #In the paramters as you can see, tag list is under ad:
    #"ad"=>{"URL"=>"http://123.234.12.3:8380/sdsd.m3u8", "duration"=>"4", "description"=>"new ad", "tag_list"=>{"23"=>"1", "24"=>"1"}}
  end
  
   def self.search(search)
      if search
        find(:all, :conditions => ['description LIKE ? or URL LIKE ?', "%#{search}%", "%#{search}%"])
      else
        find(:all)
      end
  end
  
end

app/controllers/backend/ads_controller.rb
class Backend::AdsController < Backend::ResourceController
   
  # GET /products
  # GET /products.json
  def index
    #@ads = Ad.all
    @ads2 = Ad.order(:url).search(params[:search])
    #@ads= @ads2.page(params[:page]).per(3)
    #.search(params[:search])
    @ads=Kaminari.paginate_array(@ads2).page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ads }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @ad = Ad.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ad }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @ad = Ad.new
    #@ad.tags.build
    #get_all_tags

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ad }
    end
  end
  
  def get_all_tags
    @tags = Tag.find(:all, :order => 'name')
  end

  # GET /products/1/edit
  def edit
    @ad = Ad.find(params[:id])
    #get_all_tags
  end

  # POST /products
  # POST /products.json
  def create
    @ad = Ad.new(params[:ad])
    #get_all_tags
    respond_with(@ad) do |format|
      if @ad.save
        format.html { redirect_to backend_ad_path(@ad), notice: 'Ad was successfully created.' }
        format.json { render json: @ad, status: :created, location: @ad }
      else
        #flash[:error]= 'eeror'
        format.html { render action: "new" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    #params[:tags] ||= {}
    @ad = Ad.find(params[:id])
    #get_all_tags
    
    respond_to do |format|
      if @ad.update_attributes(params[:ad])
        format.html { redirect_to backend_ad_path(@ad), notice: 'Ad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @ad = Ad.find(params[:id])
    @ad.destroy

    respond_to do |format|
      format.html { redirect_to backend_ads_url }
      format.json { head :no_content }
    end
  end
  
  
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ActionController::Base
  protect_from_forgery
end

#I'm inheriting from the action controller  not the application controller.. 
# to be completely separated

app/controllers/backend/application_responder.rb
class Backend::ApplicationResponder < ActionController::Responder
  include Responders::FlashResponder
  include Responders::HttpCacheResponder

  # Uncomment this responder if you want your resources to redirect to the collection
  # path (index action) instead of the resource path for POST/PUT/DELETE requests.
  # include Responders::CollectionResponder
  def initialize(*)
    super
    @flash_now = :on_failure
  end
end

app/controllers/backend/resource_controller.rb
#require "application_responder"
class Backend::ResourceController < Backend::ApplicationController
  inherit_resources
  respond_to :html
  self.responder = Backend::ApplicationResponder
  before_filter :authenticate_administrator!
 
end

app/controllers/backend/sessions_controller.rb
class Backend::SessionsController < Devise::SessionsController
  #layout "backend/sign_in"
  layout "backend"
  self.responder = Backend::ApplicationResponder
end

app/helpers/backend/ads_helper.rb
module Backend::AdsHelper
end

app/helpers/backend/application_helper.rb
module Backend::ApplicationHelper
end

app/helpers/backend/resource_helper.rb
module Backend::ResourceHelper
end

app/views/backend/ads/_form.html.erb
<%= simple_form_for [ :backend, resource ], :wrapper => :inline do |f| %>
  <fieldset>
    <legend>Fields</legend>
    <% @attributes.each do |attr| %>
      <%= f.input attr %>
    <% end %>
    <%= f.association :tags %>
    
  </fieldset>
    
  <%= f.submit :class => "primary" %>
<% end %>

app/views/backend/ads/edit.html.erb
<h1>Editing ad</h1>

<% @attributes = resource_class.attribute_names - %w(id created_at updated_at) %>
<%= render "form", :attributes => @attributes %>


<%= link_to 'Show', backend_ad_path(@ad) %> |
<%= link_to 'Back', backend_ads_path %>

app/views/backend/ads/index.html.erb
<% content_for :header do %>
  <h1>Advertisements</h1>
<% end %>

<ul class="tabs">
	<li class="active"><%= link_to "Index", "#" %></li>
	<li><%= link_to "New", new_backend_ad_path %></li>
</ul>

<table class="zebra-striped">
	<thead>
  <tr>
    <th>Url</th>
    <th>Duration</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<% @ads.each do |ad| %>
  <tr>
    <td><%= ad.url %></td>
    <td><%= ad.duration %></td>
    <td><%= ad.description %></td>
    <td class="row-actions"><%= link_to 'Show', backend_ad_path(ad) %></td>
    <td class="row-actions"><%= link_to 'Edit', edit_backend_ad_path(ad) %></td>
    <td class="row-actions"><%= link_to 'Destroy', backend_ad_path(ad), confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<div><%= paginate @ads %></div>

<% content_for :sidebar do %>
	<% form_tag backend_ads_path, :method => 'get' do %>
	  <p>
	    <%= text_field_tag :search, params[:search] %>
	    <%= submit_tag "Search", :name => nil %>
	  </p>
	<% end %>
<% end %>
<!-- <%= link_to 'New Ad', new_backend_ad_path %> -->

app/views/backend/ads/new.html.erb
<% content_for :header do %>
  <h1>New Advertisement</h1>
<% end %>

<ul class="tabs">
	<li><%= link_to "Index", backend_ads_path %></li>
	<li class="active"><%= link_to "New", "#" %></li>
</ul>
<div >
	
<% @attributes = resource_class.attribute_names - %w(id created_at updated_at) %>
<%= render "form", :attributes => @attributes %>
	
<!-- <%= render 'form' %> -->

<%= link_to 'Back', backend_ads_path %>

</div>

app/views/backend/ads/show.html.erb
<ul class="tabs">
	<li><%= link_to "Index", backend_ads_path %></li>
	<li><%= link_to "New", new_backend_ad_path %></li>
	<li class="active"><%= link_to "Show", "#" %></li>
	<li><%= link_to "Edit", edit_backend_ad_path %></li>
	<li><%= link_to "Destroy", backend_ad_path(@ad), :method => :delete, :confirm => "Are you sure?" %></li>
</ul>



<p>
  <b>Url:</b>
  <%= @ad.url %>
</p>

<p>
  <b>Duration:</b>
  <%= @ad.duration %>
</p>

<p>
  <b>Description:</b>
  <%= @ad.description %>
</p>

<p>
	<b>Tags:</b>
	<% @ad.tags.each do |tag|%>
		<%= tag.name %>
	<% end %>
</p>


<%= link_to 'Edit', edit_backend_ad_path(@ad) %> |
<%= link_to 'Back', backend_ads_path %>